// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NopOperator) DeepCopyInto(out *NopOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NopOperator.
func (in *NopOperator) DeepCopy() *NopOperator {
	if in == nil {
		return nil
	}
	out := new(NopOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NopOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NopOperatorList) DeepCopyInto(out *NopOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NopOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NopOperatorList.
func (in *NopOperatorList) DeepCopy() *NopOperatorList {
	if in == nil {
		return nil
	}
	out := new(NopOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NopOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NopOperatorSpec) DeepCopyInto(out *NopOperatorSpec) {
	*out = *in
	if in.Operators != nil {
		in, out := &in.Operators, &out.Operators
		*out = make([]OperatorChannel, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NopOperatorSpec.
func (in *NopOperatorSpec) DeepCopy() *NopOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(NopOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NopOperatorStatus) DeepCopyInto(out *NopOperatorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NopOperatorStatus.
func (in *NopOperatorStatus) DeepCopy() *NopOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(NopOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorChannel) DeepCopyInto(out *OperatorChannel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorChannel.
func (in *OperatorChannel) DeepCopy() *OperatorChannel {
	if in == nil {
		return nil
	}
	out := new(OperatorChannel)
	in.DeepCopyInto(out)
	return out
}
