apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nopoperators.operators.nefeli.eu
spec:
  group: operators.nefeli.eu
  names:
    kind: NopOperator
    listKind: NopOperatorList
    plural: nopoperators
    singular: nopoperator
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: NopOperator is the Schema for the nopoperators API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: NopOperatorSpec defines the desired state of NopOperator
          properties:
            operators:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                description: 'EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
                  NOTE: json tags are required.  Any new fields you add must have
                  json tags for the fields to be serialized.'
                properties:
                  name:
                    type: string
                  replicas:
                    type: integer
                  url:
                    type: string
                  version:
                    type: string
                required:
                - name
                - url
                - version
                type: object
              type: array
          required:
          - operators
          type: object
        status:
          description: NopOperatorStatus defines the observed state of NopOperator
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
